EntityaToBD
msk-itstep-org/jv1911-khvorostiuk pull request #2
Opened 2019-11-26 21:53 UTC by Acceil

2019-11-27 08:43 UTC, const-se requested changes
Во-первых, зачем в проект добавлена зависимость от модуля Security? Пока рано ее добавлять.
Во-вторых, очень плохая идея - сделать каталог товаров енамом. А если завтра прибежит менеджер и потребует добавить новый каталог? Придется делать правку в коде, что не очень быстро (сборка проекта, тестирование, деплой на продакшн). Поэтому нужно переделать каталог в сущность и хранить каталоги в базе.
В-третьих, сорри, не заметил в прошлый раз, что был удален файл local.properties.dist. Спасибо, что вернули.
Все правки нужно сделать в этой же ветке EntityaToDB, они автоматом подтянутся в данный Pull Request.

2019-12-03 09:12 UTC, const-se requested changes
Осталось совсем немного правок

2019-12-03 09:12 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Good.java
>      private Double price;
Цену (и вообще деньги) лучше хранить в Integer, причем суммы хранить именно в копейках. То есть 150 руб = 15000. Это нужно для того, чтобы избежать ошибок округления при арифметических операциях

2019-12-03 09:12 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/User.java
> +    @Column
Телефон не может быть NULL? То есть обязателен к заполнению? Просто интересуюсь

2019-12-03 09:12 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Good.java
> +    private String manufacturer;
Что это? И почему в базе это уникальный столбец, а здесь в аннотации не указано unique = true?

2019-12-03 09:20 UTC, Acceil commented on src/main/java/org/itstep/msk/app/entity/User.java
> +    @Column
Думаю да, потому что нужен для доставки )

2019-12-03 22:28 UTC, const-se approved these changes

2019-12-03 22:28 UTC, merged